### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sasuw** [valfirst/slf4j-test#124]
Could you provide an explicit license for your project? I have seen the "License" section in your README.md file, but it is only a license scan without mentioning the license of your part of the code (as far as I can see). I'd like to use it in my project, but cannot do so if there's no license.

You base your project on slf4j-test by Robert Elliott. That project uses the MIT X11 license, see **http://projects.lidalia.org.uk/slf4j-test/license.html** If you are ok with that license, maybe you could use the same license for your code?

**Comment by valfirst** [comment]
hi @sasuw, do you need a new release as well?
