### ISSUE TITLE
LoggingEvent#getFormattedMessage() doesn't format nulls the same way as SLF4J

### ISSUE THREAD

**Issue by josephw** [valfirst/slf4j-test#220]
`LoggingEvent#getFormattedMessage()` is public (#23). However, it doesn't present `null` values the same way as SLF4J, due to un-matched wrapping/unwrapping of `Optional`:
```
        LoggingEvent e = new LoggingEvent(Level.INFO, "Content: {}, {}", null, "value");
        System.out.println(e.getFormattedMessage());
```

Produces:
```
Content: Optional.empty, value
```
Rather than the expected:
```
Content: null, value
```

(Reposted from https://github.com/Mahoney/slf4j-test/issues/31)

**Comment by valfirst** [comment]
@josephw do you need a release for this fix?
