### ISSUE TITLE
Add a Thread Context Classloader attribute on LoggingEvent

### ISSUE THREAD

**Issue by sofiamorseletto** [valfirst/slf4j-test#250]
Hi! I'd like to add an attribute on LoggingEvent which contains the Thread Context Classloader used when the logging event was created. This would allow me to assert the TCCL of a certain log to check that the log was handled by the correct classloader. As far as I know I would only have to add the extra attribute with its getter method and an additional test. Is there anything else I should take into account?

The attribute would be on LoggingEvent as following:

```java
public class LoggingEvent {

    private final Level level;
    private final ImmutableMap<String, String> mdc;
    private final Optional<Marker> marker;
    private final Optional<Throwable> throwable;
    private final String message;
    private final ImmutableList<Object> arguments;

    private final Optional<TestLogger> creatingLogger;
    private final Instant timestamp = new Instant();
    private final String threadName = Thread.currentThread().getName();
    private final ClassLoader threadContextClassLoader =
            Thread.currentThread().getContextClassLoader();

    // Class Methods
}
```

**Comment by sofiamorseletto** [comment]
Thank you for taking a look at this so quickly! Is there any chance a release could be made with this change?

**Comment by valfirst** [comment]
@sofiamorseletto thank you for PR, the changes will be released within 3 days

**Comment by valfirst** [comment]
@sofiamorseletto release `2.6.0` is published
