### ISSUE TITLE
Provide a mechanism to limit default behaviour of capturing all logging

### ISSUE THREAD

**Issue by josephw** [valfirst/slf4j-test#314]
I'd like some way to prevent existing test cases that generate huge amounts of logging from having performance impact.

I added `slf4j-test` to a large multi-module build with existing tests, successfully. Later, I noticed one test had become dramatically slower. On investigation, a third-party component was logging a _huge_ volume at `DEBUG`: hundreds of thousands, repeated across tens of tests. Storing that was impacting the runtime measurably, adding minutes to that module's build. As a workaround, I identified the specific loggers (several) and added code to disable them individually using `setEnabledLevelsForAllThreads()`.

I'd like a more general mechanism to prevent this. If possible, one that's opt-*out*, rather than opt-in, to avoid needing to change existing tests.

Some possible ways to implement this, with varying degrees of impact on existing tests:
* default to capturing `INFO` and above
* have a default limit to the number of events that will be retained
* allow setting an `enable.level` through `slf4jtest.properties`
* print a noisy alert of loggers with unexpectedly high volume
* a more general utility method to disable logging for a whole hierarchy of loggers
* a single utility method to disable _all_ logging, and require subsequent tests to opt back in

The workaround is easy. Just a case where having this handled would have saved me some time.

**Comment by youribonnaffe** [comment]
I have a similar issue where using slf4j-test is making a ArchUnit test execution 10x slower (from ~1s to ~10s). ArchUnit is producing a lot of traces when it is scanning classes.

Having a global setting to decide which levels are captured would solve the issue. Is it something that can be considered? I'll be happy to contribute some code around it.

**Comment by valfirst** [comment]
> Having a global setting to decide which levels are captured would solve the issue. Is it something that can be considered? I'll be happy to contribute some code around it.

yes, I think such option might be useful, system properties or properties file could be used for configuration. And contributions are highly welcome 😄

**Comment by josephw** [comment]
> making a ArchUnit test execution 10x

I should add that the third-party component causing the problem in my case was also ArchUnit 😄.

**Comment by youribonnaffe** [comment]
Here is an attempt for this: https://github.com/valfirst/slf4j-test/pull/324
I mostly took inspiration from the existing print level setting.
