### ISSUE TITLE
Eliminate unneccesary dependencies

### ISSUE THREAD

**Issue by karstenspang** [valfirst/slf4j-test#380]
A library should not put unneccessary burdens on its clients, with regard to dependency management. Also, the focus on vulnerabilities in third party dependencies, prompts for reducing the number of transitive dependencies as much as possible.

There the following kinds of dependencies in SLF4J Test:
* SLF4J itself. Obviously, if the client is not using SLF4J, the client will have no need for SLF4J Test.
* Optional dependencies on test frameworks. Again, this is not problem. For example, only if the client is already using JUnit 4, the client will have use for the `TestLoggerFactoryResetRule` class.
* General purpose libraries, originally introduced because JDK and/or SLF4J did not have the functionality built in. These are Guava, Joda Time, and the Lidalia SLF4J Extensions.
* Test dependencies. They are not transitive and thus do not burden the client.

The objective of this issue is to eliminate the general purpose libraries from SLF4J Test.

I have already made these changes to a fork of the original SLF4J Test, and it should be possible to apply them to this fork with little extra work.

## Principles

The changes must not impact basic use of SLF4J Test. This means that mainstream test code like
```
TestLogger logger=TestLoggerFactory.getTestLogger(MyClass.class);
logger.clear();
MyClass.doSomething();
List<LoggingEvent> events=logger.getLoggingEvents();
List<LoggingEvent> expected=List.of(
    LoggingEvent.debug("debug message"),
    LoggingEvent.error("error message")
);
assertEquals(expected,events);
```
just needs to be compiled with the new version to work just as before. We do not attempt binary compatibility. Test code is usually compiled every time it is executed anyway.

## Overview of API changes

These are the classes visible to the client, i.e. as parameters or return values, that need to be replaced by classes available in Java 8 and SLF4J with equivalent, but different, functionality.

| Current | Replacement | Comments |
|---------|-------------|----------|
|`uk.org.lidalia.slf4jext.Level`|`org.slf4j.event.Level`|The levels are in the opposite order.|
|`com.google.common.base.Optional`|`java.util.Optional`|The API is different.|
|`org.joda.time.Instant`|`java.time.Instant`|The API is different.|
|`com.google.common.collect.ImmutableList`/`Map`/`Set`|`java.util.List`/`Map`/`Set`|Return values shall still be immutable.|

## `Level`
The `org.slf4j.event.Level` class has been present in SLF4J since version 1.7.15 from 2016. There is little reason for a client to use a version older than that.

Changing the `import` statement from one package to the other handles most of the changes. But some differences between the two `Level` classes remain.

### Ordinal Values

In `uk.org.lidalia.slf4jext.Level`, `ERROR` has the lowest ordinal value, and `TRACE` has the highest. In `org.slf4j.event.Level`, it is the other way round. When comparing levels using `Enum.compareTo`, the equality sign will have to be reversed. In SLF4J Test, this is used to decide whether to print the log message.

### `OFF` Level

`org.slf4j.event.Level` has no `OFF` level. This means that another way must be used to specify that printing is off. `null` is the only other value you can pass as an enum. The print level logic needs to be changed to use `null` as "off".

### `enableableLevels`

`uk.org.lidalia.slf4jext.Level` has the static method `enableableLevels` that returns the set of enum values corresponding to log levels that can be enabled. Since all values represent enableable levels in `org.slf4j.event.Level`, `EnumSet.allOf(Level.class)` provides the equivalent funtionality.

## `Instant`

See also #312

Apart from changin the `import`, there are two important differences between the two `Instant` implementation.

### Setting of a clock

While Joda Time allows to set the clock on a global level for test purposes, this must be handled by the user code itself for the `java.time.Instant`. Specifically, initialization must use `Instant.now(Clock)`, and there must be a facility allowing setting of the clock.

A `ThreadLocal<Clock>` variable needs to be added to the `LoggingEvent` class, as well as a package private method to set it for test purposes. The initial value needs to be obtained using `Clock::systemUTC`. A method to set the clock for all threads must be provided as well.

The rule to set the clock in Joda Time to be fixed at the epoch used in `LoggingEventTests` must be replaced by one calling the method in `LoggingEvent`.

### Format

The `org.joda.time.Instant.toString` methods formats the time with millisecond precision, whereas `java.time.Instant.toString` provides second precision only.

A `DateTimeFormatter` must be added to `LoggingEvent` for printing the message with millisecond precision.

## `Optional`

The two `Optional` classes provide essentially the same functionality, but the method names differ. For example `fromNullable` becomes `ofNullable`, `or` becomes `orElse`, and `transform` becomes `map`. The two latter are changed from using a Guava `Provider` 
or `Function` to a `java.util.function.Provider` or `java.util.function.Function`.

## Collections

Parameter and return types are changed to be simply `List`, `Map`, or `Set`, instead of the specific ones from Guava. The client can still pass the Guava ones as parameters if needed. In case the client assign a returned value to a specific type, code changes are needed.

Returned vales are to be wrapped using `java.util.Collections.unmodifiableList`/`Map`/`Set`, possibly after copying.

Internal values are to be implemented using `ArrayList`, `HashMap`, or `HashSet`, possibly wrapped to be made unmodifiable. As a special case, enabled log level sets are to be represented as `EnumSet<Level>`.

**Comment by karstenspang** [comment]
I see that you have already replaced `Optional` and have an issue for `Instant`.
I can create two PR's for `Level` and for the collection types, even though they would probably conflict.
I see that you have created more functionality using `Level`. These are not covered by the changes I already made, but it should be just a matter of changing imports. That will introduce incompatibility, which again can be fixed by changing imports in the client code.

**Comment by valfirst** [comment]
@karstenspang please proceed with PR-s.

> That will introduce incompatibility, which again can be fixed by changing imports in the client code.

Breaking changes are ok, once they are introduced in `3.0.0`. So I think it's time to move forward

**Comment by karstenspang** [comment]
This was the first PR. I can see that if I remove the Guava collections on a branch based on master, it will have quite a few conflicts with this one (collections of levels). Should I just create the new branch from this one?

**Comment by valfirst** [comment]
> Should I just create the new branch from this one?

Yes, I think, I'll merge the first PR once comments are resolved

**Comment by valfirst** [comment]
@karstenspang I think all items from this ticket are done, right?

**Comment by karstenspang** [comment]
All done now
