### ISSUE TITLE
Null inputs replaced

### ISSUE THREAD

**Issue by karstenspang** [valfirst/slf4j-test#390]
At least two places, nulls are replaced by other values:
* When a `LoggingEvent` is constructed with arguments, nulls are replaced by `Option.empty()`
* If a null value is inserted in the MDC, it replaced by the string `"null"`.

I am not sure what was the rationale for implementing it like this. For the first case, it may beacuse the original author wanted to use the Guava `ImmutableList`. But it also seems that he had a dislike for `null` in general.
If you just compare logging events, the first has no impact, but if you are testing MDC functionality, the second could be annoying. In particular, the assertion failure message shows `null` in both the expected and the actual value.

I can quickly make a PR to change this if you think it is a good idea.

**Comment by valfirst** [comment]
not sure what impact will be, but let's try, please proceed with PR
