### ISSUE TITLE
Do we really need copies to be immutable?

### ISSUE THREAD

**Issue by karstenspang** [valfirst/slf4j-test#391]
When I made the changes to the collections from Guava to JDK, I made collection return values immutable, just to make thing work like before. But is there really a reason to wrap a copy of the value using `Collections.unmodifiableXXX` ?

**Comment by valfirst** [comment]
if it's an explicit copy (`getCopy...`), then I don't see reason to make it unmodifiable; if it's a regular getter, probably we don't need to have a copy before returning immutable collection
