### ISSUE TITLE
Setting enabled logging levels for all threads change the default for all threads

### ISSUE THREAD

**Issue by karstenspang** [valfirst/slf4j-test#393]
Calling `TestLogger.setEnabledLevelsForAllThreads` works by changing the default value for all threads, meaning that if any thread calls `TestLogger.clear` or even `TestLogger.clearAll`, the value is not reset to all levels. It would be better if only the current value was changed.

I can implement this, perhaps within a month.

**Comment by karstenspang** [comment]
My intended fix will also solve [this issue from sonarcloud](https://sonarcloud.io/project/issues?open=AYhHcCtuR40UQDprr1PY&id=com.github.valfirst%3Aslf4j-test).

**Comment by valfirst** [comment]
@karstenspang thank you!
