### ISSUE TITLE
Support for fluent API

### ISSUE THREAD

**Issue by karstenspang** [valfirst/slf4j-test#407]
We should better support the SLF4J fluent API. In particular, markers are not handled correctly.
For example, the classic
```
logger.warn(MarkerFactory.getMarker("ABC"),"Invalid timestamp {}","20XX-07-15 20:14:31.0");
```
results in
```
LoggingEvent{level=WARN, mdc={}, marker=Optional[ABC], throwable=Optional.empty, message='Invalid timestamp {}', arguments=[20XX-07-15 20:14:31.0]}
```
but the fluent
```
logger.atWarn().addMarker(MarkerFactory.getMarker("ABC")).log("Invalid timestamp {}","20XX-07-15 20:14:31.0"));
```
results in
```
LoggingEvent{level=WARN, mdc={}, marker=Optional.empty, throwable=Optional.empty, message='ABC Invalid timestamp {}', arguments=[20XX-07-15 20:14:31.0]}
```
This is caused by the way `org.slf4j.spi.DefaultLoggingEventBuilder` works. If the logger does not implement the `org.slf4j.spi.LoggingEventAware` interface, `DefaultLoggingEventBuilder.log()` prepends the marker to the message. If the logger does implement the interface, it's `log(org.slf4j.event.LoggingEvent)` method is called.

The obvious way to solve this issue is of course to have `TestLogger` implement `LoggingEventAware`. However, the interface was introduced in SLF4J 2.0.0, so it is not possible to maintain compatibility with SLF4J 1.7 and 1.8. It will probably be possible to implement this only after support for older versions of SLF4J is dropped.

There are further new features in the fluent API:
* It is possible to have several markers. The existing marker in `LoggingEvent` shall be made a `List` instead of an `Optional`. The classic methods sets it to either an empty list or a singleton list, depending on whether the marker is present.
* A new key/value pair list is added. A new member shall be added to `LoggingEvent` to store this. The classic methods sets it to an empty list. Currently, they will also be prepended to the message.

I don't think that this should be implemented right now, unless a backward compatible way is found.

**Comment by valfirst** [comment]
Compatibility with SLF4J 1.X is not kept due to changes in SFL4J API, see more details: https://github.com/valfirst/slf4j-test#compatibility-matrix

**Comment by karstenspang** [comment]
In that case, I will start implementing this, probably next week.

**Comment by karstenspang** [comment]
I realized that further changes are needed for key/value pairs and multiple markers, mainly in `TestLoggerAssert`. I have done the changes and I am working on test cases.
